name: Docker Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t myapp:latest .

    - name: Login to Docker Hub
      if: success()
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push Docker image
      if: success()
      run: docker tag myapp:latest ${{ secrets.DOCKER_USERNAME }}/myapp:latest
      run: docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Pull Docker image
      run: docker pull ${{ secrets.DOCKER_USERNAME }}/myapp:latest

    - name: Run Docker container
      run: docker run -d -p 8080:80 ${{ secrets.DOCKER_USERNAME }}/myapp:latest
